### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'trans'.

### ISSUE THREAD

**Issue by tsoawcn** [frankli0324/ctfd-pages-theme#6]
我在安装好的 CTFd 3.5.0 上，跟着视频创建路由成功，最后切换主题为 pages 后，出现 Internal Server Error，执行 docker-compose logs -f ctfd，看到如下信息，麻烦大佬看看是什么问题，谢谢！
```
ctfd_1   | ERROR [CTFd] Exception on / [GET]
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
ctfd_1   |     response = self.full_dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
ctfd_1   |     rv = self.handle_user_exception(e)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
ctfd_1   |     return original_handler(e)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
ctfd_1   |     reraise(exc_type, exc_value, tb)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
ctfd_1   |     raise value
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
ctfd_1   |     rv = self.dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
ctfd_1   |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd_1   |   File "/opt/CTFd/CTFd/views.py", line 367, in static_html
ctfd_1   |     return render_template("page.html", content=page.html, title=page.title)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
ctfd_1   |     return _render(
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
ctfd_1   |     rv = template.render(context)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
ctfd_1   |     self.environment.handle_exception()
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
ctfd_1   |     reraise(*rewrite_traceback_stack(source=source))
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
ctfd_1   |     raise value.with_traceback(tb)
ctfd_1   |   File "/opt/CTFd/CTFd/themes/pages/templates/page.html", line 1, in top-level template code
ctfd_1   |     {% extends "base.html" %}
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 96, in _load_template
ctfd_1   |     template = self.loader.load(self, name, globals)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
ctfd_1   |     reraise(*rewrite_traceback_stack(source=source))
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
ctfd_1   |     raise value.with_traceback(tb)
ctfd_1   |   File "/opt/CTFd/CTFd/themes/pages/templates/base.html", line 49, in template
ctfd_1   |     {% trans %}Powered by CTFd{% endtrans %}
ctfd_1   | jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'trans'.
```

**Comment by tsoawcn** [comment]
安装最新版的CTFd分页正常了，可是 ctfd-whale 的题目在这个 theme 下都跳不出来，core beta 也一样，core 下正常

**Comment by frankli0324** [comment]
前段时间drop了3.5的支持，由于主题改的地方并不多，可以按照commit自己照着core beta的老版本修改
对于ctfd whale，近期会支持3.6。工作以来比较忙

**Comment by frankli0324** [comment]
老版本push到了core-beta-3.5.x分支 cc @imLZH1
